import { Injectable } from '@angular/core';
import { DateTime } from 'luxon';
import { BehaviorSubject, Subject } from 'rxjs';
import { Task } from '../models/task';

@Injectable({
  providedIn: 'root',
})
export class TaskService {
  private generatedId = 0;

  tasks: Task[] = [];
  taskSubject: Subject<Task[]>;
  subtaskSubject: Subject<Task>;

  constructor() {
    this.taskSubject = new BehaviorSubject<Task[]>(new Array<Task>());
    // this sends the parent task for a listener to see what subtasks have changed
    this.subtaskSubject = new Subject<Task>();
  }

  /**
   * Adds a main task with the given name/description
   * @param taskName Description of the task to add
   */
  addTask(taskName: string): void {
    // the id would normally be generated by the DB, but don't have one right now.
    const task = {
      name: taskName,
      date: DateTime.local(),
      id: this.generatedId.toString(),
      complete: false,
    };
    this.generatedId++;
    this.tasks.push(task);
    // return a copy of the original array, this way nobody can modify the array outside of the service.
    this.taskSubject.next(this.tasks.slice());
  }

  /**
   * Removes the specified task from the service
   * @param taskId TaskID to remove
   */
  removeTask(taskId: string): void {
    const index = this.tasks.findIndex((task: Task) => task.id === taskId);
    if (index > -1) {
      this.tasks.splice(index, 1);
    }
    // return a copy of the original array, this way nobody can modify the array outside of the service
    this.taskSubject.next(this.tasks.slice());
  }

  /**
   * Adds a subtask to the given parent task
   * @param taskId Parent taskID to associate the new subtask to
   * @param subtaskName Subtask name/desciption to add
   */
  addSubTask(taskId: string, subtaskName: string): void {
    const index = this.tasks.findIndex((t: Task) => t.id === taskId);

    // the id would normally be generated by the DB, but don't have one right now.
    const subtask = {
      name: subtaskName,
      date: DateTime.local(),
      id: this.generatedId.toString(),
      complete: false,
    };
    this.generatedId++;
    const parentTask = this.tasks[index];
    if (parentTask.subtask === undefined) {
      parentTask.subtask = [];
    }
    this.tasks[index].subtask?.push(subtask);
    this.subtaskSubject.next(this.tasks[index]);
  }

  /**
   * Removes a subtask from the given task
   * @param taskId Parent taskId
   * @param subtaskId Id of the subtask to remove
   */
  removeSubTask(taskId: string, subtaskId: string): void {
    const task: Task[] = this.tasks.filter((t: Task) => t.id === taskId);

    if (task.length === 1) {
      const index = task[0].subtask?.findIndex(
        (st: Task) => st.id === subtaskId
      );
      if (index !== undefined && index > -1) {
        task[0].subtask?.splice(index, 1);
      }
    }
  }

  /**
   * This will mark a task complete/not complete, including any subtasks.  This will mark all subtasks the same as the parent
   * @param taskId Task ID to mark complete/not complete.
   * @param complete True if the task is complete, false if the task should be marked not complete
   */
  taskComplete(taskId: string, complete: boolean): void {
    const task: Task[] = this.tasks.filter((t: Task) => t.id === taskId);

    if (task.length === 1) {
      task[0].complete = complete;
      this.taskSubject.next(this.tasks.slice());
      // mark all subtasks as complete as well
      if (task[0].subtask) {
        task[0].subtask.forEach((subtask: Task) => {
          subtask.complete = complete;
        });
        this.subtaskSubject.next(task[0]);
      }
    }
  }

  /**
   * Marks a subtask as complete/not complete
   * @param parentTaskId Parent task ID
   * @param subtaskId Subtask ID
   * @param complete True to mark task as complete, false to mark it as not complete
   */
  subtaskComplete(
    parentTaskId: string,
    subtaskId: string,
    complete: boolean
  ): void {
    const task: Task[] = this.tasks.filter((t: Task) => t.id === parentTaskId);
    if (task.length === 1) {
      if (task[0].subtask) {
        // find the subtask
        const subtask: Task[] = task[0].subtask.filter((st: Task) => st.id === subtaskId);
        if (subtask.length === 1) {
          subtask[0].complete = complete;
          this.subtaskSubject.next(task[0]);
        }
      }
    }
  }
}
